[package]
name = "exploit"
version = "0.1.0"
authors = ["irishmaestro"]
repository = "https://github.com/irishmaestro/hackthebox"
description = "exploit for hackthebox challenge web_diogenes_rage"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.25"
reqwest = { version = "0.11", features = ["json", "cookies"] }
tokio = { version = "1", features = ["full"] }
